#!/bin/bash
BREAK="============================================================"
if [ $# == 0 ]; then
    filesystem="/"
    echo $filesystem
elif [ $# == 2 ] && [ $1 == '-f' ]; then
    filesystem=$2
    echo $filesystem
fi

echo -ne "\n $BREAK \n \t Disk Usage for filesystem $(date +'%F') \n $BREAK \n\n";
df -hP $filesystem;

echo -ne "\n $BREAK \n \t Volume Group Usage $(date +'%F') \n $BREAK \n\n";
vgs $(df -h $filesystem | grep dev | awk '{print $1}'| cut -d\- -f1| cut -d\/ -f4);

echo -ne "\n $BREAK \n \t Largest Folders:$filesystem $(date +'%F') \n $BREAK \n\n";
du -xSk $filesystem | sort -rn | head -20|awk '{printf "%d MB\t%s\n",($1/1024),$NF}' ;

echo -ne "\n $BREAK \n \t Largest Files:$filesystem \n $BREAK \n\n";
find $filesystem -mount -type f -ls|sort -rnk7 |head -20|awk '{printf "%d MB\t%s\n",($7/1024)/1024,$NF}';

echo -ne "\n $BREAK \n \t List of All Open Files \n $BREAK \n\n";
function  check_os {
        if [[ $(cat /etc/os-release 2>&1 | grep '^ID' | awk '{print $1}' 2>&1 )  = *debian* ]]; then
        echo "... ...";
        elif [[ $(cat /etc/os-release 2>&1 | grep '^ID' | awk '{print $1}'  2>&1 )  != *debian* ]]; then
        echo "...";
        fi
}
check_os
ver=$(check_os)
function package_installed {
        if [[ $ver = "... ..." ]]; then
         if [ `dpkg -l | grep -i lsof | wc -l` -lt 1 ]; then
           apt-get install lsof  | grep -i 'Total download\|Installed:' -A1;
        fi
fi
}
package_installed
function package_installeda {
        if [[ $ver == "..." ]]; then
           if [[ `rpm -qa | grep -i lsof | wc -l` -lt 1 ]]; then
                yum  install lsof;
                fi
        fi
}
package_installeda;

echo -ne "\n $BREAK \n \t Open Deleted Files:$filesystem \n $BREAK \n\n";
lsof 2> /dev/null | grep $filesystem | grep deleted | wc -l
lsof 2> /dev/null | grep $filesystem | grep deleted| awk '{ if($7 > 1048576) print $7/1048576, "MB ",$9,$1 }' | sort -n -u | tail;
